#!/bin/bash
	if [ $# -eq 3 ]
	then
		case $2 in
		+) echo "$1 + $3 = `expr $1 + $3`";;
		-) echo "$1 - $3 = `expr $1 - $3`";;
		/) echo "$1 / $3 = `expr $1 / $3`";;
		*) echo "$1 * $3 = `expr $1 \* $3`";;
		%) echo "$1 % $3 = `expr $1 % $3`";;
		esac
	else
		echo "Not enough input"i
	fi
exit 0
